export const GROUP_MANAGEMENT_LIST = "GROUP_MANAGEMENT_LIST";

export const GROUP_MANAGEMENT_LIST_PAGE = "GROUP_MANAGEMENT_LIST_PAGE";

export const GROUP_MANAGEMENT_INITIATOR = "GROUP_MANAGEMENT_INITIATOR";

export const GROUP_MANAGEMENT_TYPE = "GROUP_MANAGEMENT_TYPE";

export const GROUP_MANAGEMENT_TIME = "GROUP_MANAGEMENT_TIME";

export const GROUP_MANAGE_ID = "GROUP_MANAGE_ID";

export const GROUP_EVENT_STATUS = "GROUP_EVENT_STATUS";

export const GROUP_EVENT_VALUE = "GROUP_EVENT_VALUE";
