export const MARKET_MONITORING_LIST = "MARKET_MONITORING_LIST";

export const MARKET_MONITORING_INPUT_VAL = "MARKET_MONITORING_INPUT_VAL";

export const MARKET_MONITORING_ACTIVE_TIME = "MARKET_MONITORING_ACTIVE_TIME";

export const SEARCH_LIST_PAGE_CHANGE = "SEARCH_LIST_PAGE_CHANGE";

export const SEARCH_LIST_PAGE_CHANGE_ONE = "SEARCH_LIST_PAGE_CHANGE_ONE";
export const SEARCH_LIST_PAGE_CHANGE_TWO = "SEARCH_LIST_PAGE_CHANGE_TWO";
export const SEARCH_LIST_PAGE_CHANGE_THREE = "SEARCH_LIST_PAGE_CHANGE_THREE";

export const MARKET_MONITORING_STATUS = "MARKET_MONITORING_STATUS";

export const MARKET_MONITORING_SCENE = "MARKET_MONITORING_SCENE";

export const MARKET_MONITORING_CHANNEL = "MARKET_MONITORING_CHANNEL";

export const MARKET_MONITORING_INITIATOR = "MARKET_MONITORING_INITIATOR";

export const MARKET_MONITORING_SWITCH = "MARKET_MONITORING_SWITCH";

export const MARKET_MONITORING_HISTORY_CONDITION =
  "MARKET_MONITORING_HISTORY_CONDITION";

  export const TAB_KEY = 'TAB_KEY'
