export const NORMAL_SETTING = 'NORMAL_SETTING';
export const NORMAL_SETTING_RESET = 'NORMAL_SETTING_RESET';
export const NORMAL_CHANNEL = 'NORMAL_CHANNEL';
export const NORMAL_CHANNEL_RESET = 'NORMAL_CHANNEL_RESET';